title: "Peakboard Templates – Examples for every use case"
email:  support@peakboard.com
description: "Due to the flexibility of Peakboard there are numerous application possibilities in the most diverse areas. Here you will find some templates with a short description, which you can download directly and and customize for your purposes."
url: "https://templates.peakboard.com"
twitter_username: pkbrd
github_username:  Peakboard
languages: ["en", "de", "cn"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: de
languageNames:
  de: Deutsch
  en: English
  cn: Chinese
# Analytics
gtm: "GTM-T2LNC7N"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  templates:
    output: true
    permalink: /:path
  extensions:
    output: true
    permalink: /extensions/:path

# Portions of text found throughout common components (like the footer) can be configured here for each language
language:
  en:
    article-download-button-text: "download template"
    article-download-explanation: "Open file with Peakboard Designer"
    article-overview-title: "overview"
    article-overview-description-title: "Description"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "Data Sources"
    article-related-templates-title: "related templates"
    homepage-top-section-title: "Peakboard Templates"
    homepage-top-section-content: "Due to the flexibility of Peakboard there are numerous application possibilities in the most diverse areas. Here you will find some templates with a short description, which you can download directly and and customize for your purposes."
    homepage-carousel-button-text: "learn more"
    homepage-featured-category: "recommended"
    homepage-all-category: "all"
    homepage-menu-title-category: "categories"
    homepage-menu-title-data-sources: "Data Sources"
    homepage-visible-categories: ["administration","andon","kpi","lean management","logistics","oee","production","scripting","interaction", "edge", "shopfloor"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "get started for free!"
    top-menu-cta-button-url: "https://peakboard.com/en/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "template overview"
    footer-support: "support"
    footer-support-tel: "tel:"
    footer-support-email: "e-mail:"
    footer-contact: "contact"
    footer-contact-email: "e-mail:"
    footer-contact-website: "website:"
    footer-copyright: "All rights are reserved."
    footer-github: "github"
    footer-github-text: "View this page in Github"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "Legal Information"
    footer-legal-url: "https://peakboard.com/en/legal-notice/"
    footer-privacy: "Privacy Policy"
    search-title: "Peakboard Search"
    search-results: "Results"
    search-no-results: "We didn't find any results for the search: "
    search-bar-placeholder: "search"
    cta-title: "Do you need more support?"
    cta-subtitle: "Be enlightened!"
    cta-column-one-link: "https://www.youtube.com/channel/UC2PzOvzOGg4XtKNr2OFOofA"
    cta-column-one-link-text: "Visit our YouTube channel"
    cta-column-one-text: "Our numerous videos for beginners and advanced users explain exactly how to design your dashboard."
    cta-column-two-link: "https://help.peakboard.com/en/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-two-link-text: "Visit the Peakboard Help website"
    cta-column-two-text: "Check out numerous articles that will help you use the Peakboard Designer."
    cta-column-three-link: "https://peakboard.com/en/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-three-link-text: "Visit www.peakboard.com"
    cta-column-three-text: "Find out all about Peakboard and browse our different use cases and success stories."
    cookie-box-title: "Delicious, cookies!"
    cookie-box-explanation: "We use cookies to constantly improve our websites: templates.peakboard.com, help.peakboard.com and to show you relevant content. By using our website, you agree to this."
    cookie-box-link-privacy-policy: "View our Privacy Policy"
    cookie-box-button-accept: "Accept All"
    cookie-box-button-change: "Change Privacy Preferences"
    cookie-box-change-preferences-title: "Privacy Preferences"
    cookie-box-change-preferences-explanation: "Here you will find an overview of all cookies used. You can give your consent to whole categories or display further information and select certain cookies."
    cookie-box-change-preferences-section-essential: "Essential (1)"
    cookie-box-change-preferences-section-essential-explanation: "Essential cookies enable basic functions and are necessary for the proper functioning of the website."
    cookie-box-change-preferences-section-statistics: "Statistics (1)"
    cookie-box-change-preferences-section-statistics-explanation: "Statistics Cookies collect information anonymously. This information helps us to understand how our visitors use our website."
    cookie-box-change-preferences-button-save: "Save Preferences"
    extensions-link-text-return-to-overview: "Gallery / Extensions"
    extensions-link-text-download: "download extension"
    extensions-link-how-to: "https://help.peakboard.com/data_sources/Extension/en-ManageExtension.html"
    extensions-link-text-how-to: "How to install a Peakboard Extension"
    extensions-section-description: "Description"
    extensions-section-version-history: "Version History"
    extensions-section-screenshots: "Screenshots"
  de:
    article-download-button-text: "template herunterladen"
    article-download-explanation: "Datei mit Peakboard Designer öffnen"
    article-overview-title: "overview"
    article-overview-description-title: "Description"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "Data Sources"
    article-related-templates-title: "ähnliche templates"
    homepage-top-section-title: "Peakboard Templates"
    homepage-top-section-content: "Durch die Flexibilität von Peakboard gibt es zahlreiche Anwendungsmöglichkeiten in den unterschiedlichsten Bereichen. Hier findest du einige Vorlagen mit einer kurzen Beschreibung, welche du direkt herunterladen und für deine Zwecke verwenden kannst."
    homepage-carousel-button-text: "mehr erfahren"
    homepage-featured-category: "empfohlen"
    homepage-all-category: "alle"
    homepage-menu-title-category: "Kategorien"
    homepage-menu-title-data-sources: "Datenquellen"
    homepage-visible-categories: ["administration","andon","kpi","lean management","logistik","oee / gae","produktion","scripting","interaktion", "edge", "shopfloor"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "kostenlos starten!"
    top-menu-cta-button-url: "https://peakboard.com/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "template übersicht"
    footer-support: "support"
    footer-support-tel: "tel:"
    footer-support-email: "e-mail:"
    footer-contact: "kontakt"
    footer-contact-email: "e-mail:"
    footer-contact-website: "website:"
    footer-copyright: "alle rechte vorbehalten."
    footer-github: "github"
    footer-github-text: "seite in github öffnen"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "impressum"
    footer-legal-url: "https://peakboard.com/legal-notice/"
    footer-privacy: "Privacy Policy"
    search-title: "Peakboard suche"
    search-results: "ergebnisse"
    search-no-results: "Wir haben leider nichts gefunden: "
    search-bar-placeholder: "suchen"
    cta-title: "Du benötigst weitere unterstützung?"
    cta-subtitle: "Lass dich erleuchten!"
    cta-column-one-link: "https://www.youtube.com/channel/UC2PzOvzOGg4XtKNr2OFOofA"
    cta-column-one-link-text: "Zum YouTube Kanal"
    cta-column-one-text: "Unsere zahlreichen Videos für Einsteiger und Fortgeschrittene erklären dir genau, wie du dein Dashboard gestaltest."
    cta-column-two-link: "https://help.peakboard.com/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-two-link-text: "Zur Peakboard Helpsite"
    cta-column-two-text: "Hier gibt es zahlreiche Artikel, die dir den Umgang mit dem Peakboard Designer vereinfachen."
    cta-column-three-link: "https://peakboard.com/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-three-link-text: "Zu www.peakboard.com"
    cta-column-three-text: "Auf unserer Website findest du alle wichtigen Infos zu Peakboard sowie verschiedene Anwendungsfälle und Success Stories."
    cookie-box-title: "Lecker, cookies!"
    cookie-box-explanation: "Wir verwenden Cookies, um unsere Webseiten: templates.peakboard.com, help.peakboard.com stetig zu verbessern und um dir relevante Inhalte zu zeigen. Durch die Nutzung der Website stimmst du dem zu."
    cookie-box-link-privacy-policy: "Datenschutzerklärung"
    cookie-box-button-accept: "Ich Akzeptiere"
    cookie-box-button-change: "Individuelle Datenschutzeinstellungen"
    cookie-box-change-preferences-title: "Datenschutzeinstellungen"
    cookie-box-change-preferences-explanation: "Hier finden Sie eine Übersicht über alle verwendeten Cookies. Sie können Ihre Einwilligung zu ganzen Kategorien geben oder sich weitere Informationen anzeigen lassen und so nur bestimmte Cookies auswählen."
    cookie-box-change-preferences-section-essential: "Essenziell (1)"
    cookie-box-change-preferences-section-essential-explanation: "Essenzielle Cookies ermöglichen grundlegende Funktionen und sind für die einwandfreie Funktion der Website erforderlich."
    cookie-box-change-preferences-section-statistics: "Statistiken (1)"
    cookie-box-change-preferences-section-statistics-explanation: "Statistik Cookies erfassen Informationen anonym. Diese Informationen helfen uns zu verstehen, wie unsere Besucher unsere Website nutzen."
    cookie-box-change-preferences-button-save: "Speichern"
    extensions-link-text-return-to-overview: "Gallery / Extensions"
    extensions-link-text-download: "extension herunterladen"
    extensions-link-how-to: "https://help.peakboard.com/data_sources/Extension/de-Extension.html"
    extensions-link-text-how-to: "So installierst du eine Peakboard Extension"
    extensions-section-description: "Beschreibung"
    extensions-section-version-history: "Version History"
    extensions-section-screenshots: "Screenshots"
  cn:
    article-download-button-text: "下载模板"
    article-download-explanation: "使用Peakboard Designer打开文件"
    article-overview-title: "概览"
    article-overview-description-title: "描述"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "数据源"
    article-related-templates-title: "相关模版"
    homepage-top-section-title: "获取帮助"
    homepage-top-section-content: "针对您的需求，帮助您快速、高效地充分利用Peakboard，详情请参考相关文章。"
    homepage-carousel-button-text: "了解更多"
    homepage-featured-category: "推荐"
    homepage-all-category: "全部"
    homepage-menu-title-category: "类别"
    homepage-menu-title-data-sources: "数据源"
    homepage-visible-categories: ["administration","andon","kpi","lean management","logistics","oee","production","scripting","interaction", "edge", "shopfloor"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "马上开始"
    top-menu-cta-button-url: "https://peakboard.com/zh-hans/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "模板概览"
    footer-support: "技术支持"
    footer-support-tel: "电话："
    footer-support-email: "邮箱："
    footer-contact: "联系方式"
    footer-contact-email: "电话："
    footer-contact-website: "网站："
    footer-copyright: "版权所有，保留所有权利"
    footer-github: "Github"
    footer-github-text: "前往Github查看此网页"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "法律信息"
    footer-legal-url: "https://peakboard.com/en/legal-notice/"
    footer-privacy: "隐私政策"
    search-title: "Peakboard搜索"
    search-results: "搜索结果"
    search-no-results: "未找到相关搜索结果： "
    search-bar-placeholder: "搜索"
    cta-title: "需要更多支持?"
    cta-subtitle: "其他资源"
    cta-column-one-link: "https://v.qq.com/s/videoplus/1721428022"
    cta-column-one-link-text: "访问腾讯视频"
    cta-column-one-text: "海量视频为您讲解如何设计看板，新手和高级用户同样适宜。"
    cta-column-two-link: "https://help.peakboard.com/cn/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-two-link-text: "查看Peakboard帮助"
    cta-column-two-text: "查看诸多文档，帮助您使用Peakboard Designer。"
    cta-column-three-link: "https://peakboard.cn/?utm_medium=website_info_box&utm_campaign=templates"
    cta-column-three-link-text: "浏览www.peakboard.cn"
    cta-column-three-text: "深入了解Peakboard，浏览产品不同的使用场景和客户成功案例。"
    cookie-box-title: "Cookies，美味可口!"
    cookie-box-explanation: "我们使用cookie来不断改善我们网站上的网站体验：templates.peakboard.com、help.peakboard.com并向您展示相关内容。使用本网站即表示您同意我们的cookie政策。"
    cookie-box-link-privacy-policy: "隐私权政策"
    cookie-box-button-accept: "同意所有"
    cookie-box-button-change: "更改隐私首选项"
    cookie-box-change-preferences-title: "隐私偏好"
    cookie-box-change-preferences-explanation: "您可在此查看网站使用的所有Cookies概览。您可同意所有相关设置，或者点击显示更多信息，然后勾选某些Cookies。"
    cookie-box-change-preferences-section-essential: "必要类 (1)"
    cookie-box-change-preferences-section-essential-explanation: "此类Cookies用于确保基本功能，为网站正常运行所必需。"
    cookie-box-change-preferences-section-statistics: "统计类 (1)"
    cookie-box-change-preferences-section-statistics-explanation: "此类Cookies会收集匿名信息，能帮助我们了解访客如何使用本网站。"
    cookie-box-change-preferences-button-save: "保存偏好"
    extensions-link-text-return-to-overview: "图库 / 拓件"
    extensions-link-text-download: "下载拓件"
    extensions-link-how-to: "https://help.peakboard.com/data_sources/Extension/en-ManageExtension.html"
    extensions-link-text-how-to: "如何安装Peakboard拓件"
    extensions-section-description: "描述"
    extensions-section-version-history: "版本历史"
    extensions-section-screenshots: "截图"
algolia:
  application_id: 'XEVVIEZWKI'
  index_name: PEAKBOARD_EPIC_BOARDS
  settings:
    attributesForFaceting: ['title', 'searchable(search-ignore)', 'searchable(lang)', 'searchable(category)', 'searchable(isDraft)', 'searchable(overview_data_sources)']
    searchableAttributes: ['title','unordered(content)','description','search-ignore', 'lang', 'category', 'isDraft', 'overview_data_sources']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - resources
  - docs
  - .idea
  - .idea/*
  - vendor
