title: "Peakboard Templates – Get inspired"
email:  support@peakboard.com
description: "Templates for your Peakboard. Get more out of your Peakboard experience by using one of our awesome templates."
url: "https://templates.peakboard.com"
twitter_username: pkbrd
github_username:  Peakboard
languages: ["en", "de", "cn"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: de
languageNames:
  de: Deutsch
  en: English
  cn: Chinese
# Analytics
gtm: "GTM-T2LNC7N"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap

collections:
  templates:
    output: true
    permalink: /:path

# Portions of text found throughout common components (like the footer) can be configured here for each language
language:
  en:
    article-download-button-text: "Download template"
    article-overview-title: "Overview"
    article-overview-description-title: "Description"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "Data Sources"
    article-related-templates-title: "Related Templates"
    homepage-top-section-title: "Peakboard Templates"
    homepage-top-section-content: "Due to the flexibility of Peakboard there are numerous application possibilities in the most diverse areas. Here you will find some templates with a short description, which you can download directly and use for your purposes."
    homepage-carousel-button-text: "Learn more"
    homepage-featured-category: "Recommended"
    homepage-all-category: "All"
    homepage-menu-title-category: "Categories"
    homepage-menu-title-data-sources: "Data Sources"
    homepage-visible-categories: ["Administration","Andon","KPI","Lean Management","Logistics","OEE","Production","Scripting","Reception","Interaction"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "Get started for free!"
    top-menu-cta-button-url: "https://peakboard.com/en/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "Template Overview"
    footer-support: "Support"
    footer-support-tel: "Tel:"
    footer-support-email: "E-Mail:"
    footer-contact: "Contact"
    footer-contact-email: "E-Mail:"
    footer-contact-website: "Website:"
    footer-copyright: "All rights are reserved."
    footer-github: "Github"
    footer-github-text: "View this page in Github"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "Legal Information"
    footer-legal-url: "https://peakboard.com/en/legal-notice/"
    search-title: "Peakboard Search"
    search-results: "Results"
    search-no-results: "We didn't find any results for the search: "
    search-bar-placeholder: "Search"
    cookie-alert-message: "This website uses cookies to ensure you get the best experience on our website."
    cookie-alert-button: "OK"
    cookie-alert-link-text: "Read more"
    cookie-alert-link: "https://peakboard.com/en/privacy-policy/"
    cta-title: "EXPERIENCE THE PEAKBOARD DESIGNER"
    cta-subtitle: "Make your individual visualization"
    cta-content: "Create different visualizations for production, logistics, IT and many other areas with the Peakboard Designer. Peakboard allows you to display all relevant information, KPI’s and processes at a glance and in real time."
    cta-link: "https://peakboard.com/en/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    cta-link-text: "Download the Peakboard Designer for free"
  de:
    article-download-button-text: "Template herunterladen"
    article-overview-title: "Overview"
    article-overview-description-title: "Description"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "Data Sources"
    article-related-templates-title: "Ähnliche Templates"
    homepage-top-section-title: "Peakboard Templates"
    homepage-top-section-content: "Durch die Flexibilität von Peakboard gibt es zahlreiche Anwendungsmöglichkeiten in den unterschiedlichsten Bereichen. Hier finden Sie einige Vorlagen mit einer kurzen Beschreibung, welche Sie direkt herunterladen und für Ihre Zwecke verwenden können."
    homepage-carousel-button-text: "Mehr erfahren"
    homepage-featured-category: "Empfohlen"
    homepage-all-category: "Alle"
    homepage-menu-title-category: "Kategorien"
    homepage-menu-title-data-sources: "Datenquellen"
    homepage-visible-categories: ["Administration","Andon","Empfang","KPI","Lean Management","Logistik","OEE / GAE","Produktion","Scripting","Interaktion"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "Kostenlos starten!"
    top-menu-cta-button-url: "https://peakboard.com/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "Template Übersichtsseite"
    footer-support: "Support"
    footer-support-tel: "Tel:"
    footer-support-email: "E-Mail:"
    footer-contact: "Kontakt"
    footer-contact-email: "E-Mail:"
    footer-contact-website: "Website:"
    footer-copyright: "Alle Rechte vorbehalten."
    footer-github: "Github"
    footer-github-text: "Seite in Github öffnen"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "Impressum"
    footer-legal-url: "https://peakboard.com/legal-notice/"
    search-title: "Peakboard Suche"
    search-results: "Ergebnisse"
    search-no-results: "Wir haben leider nichts gefunden: "
    search-bar-placeholder: "Suchen"
    cookie-alert-message: "Um sicherzustellen, dass Sie das beste Nutzungserlebnis auf unserer Webseite erfahren, werden Cookies verwendet."
    cookie-alert-button: "OK"
    cookie-alert-link-text: "Mehr erfahren"
    cookie-alert-link: "https://peakboard.com/datenschutzerklaerung/"
    cta-title: "ENTDECKEN SIE DEN PEAKBOARD DESIGNER"
    cta-subtitle: "Erstellen Sie Ihre individuelle Visualisierung"
    cta-content: "Mit dem Peakboard Designer erstellen Sie in kürzester Zeit ganz unterschiedliche Visualisierungen für die Produktion, Logistik, IT und viele andere Bereiche. Mit Peakboard bilden Sie alle für Sie relevanten Informationen, KPIs und Prozesse auf einen Blick und in Echtzeit ab."
    cta-link: "https://peakboard.com/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    cta-link-text: "Peakboard Designer kostenlos herunterladen"
  cn:
    article-download-button-text: "下载模板"
    article-overview-title: "Overview"
    article-overview-description-title: "Description"
    article-overview-benefits-title: "Benefits"
    article-overview-data-sources-title: "Data Sources"
    article-related-templates-title: "Related Templates"
    homepage-top-section-title: "获取帮助"
    homepage-top-section-content: "针对您的需求，帮助您快速、高效地充分利用Peakboard，详情请参考相关文章。"
    homepage-carousel-button-text: "了解更多"
    homepage-featured-category: ""
    homepage-all-category: "全部"
    homepage-menu-title-category: "类别"
    homepage-menu-title-data-sources: "数据源"
    homepage-visible-categories: ["Administration","Andon","KPI","Lean Management","Logistics","OEE","Production","Scripting","Reception","Interaction"]
    homepage-visible-data-sources:
    top-menu-cta-button-text: "马上开始"
    top-menu-cta-button-url: "https://peakboard.com/zh-hans/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    page-top-overview-text: "模板概览"
    footer-support: "技术支持"
    footer-support-tel: "电话："
    footer-support-email: "邮箱："
    footer-contact: "联系方式"
    footer-contact-email: "电话："
    footer-contact-website: "网站："
    footer-copyright: "版权所有，保留所有权利"
    footer-github: "Github"
    footer-github-text: "前往Github查看此网页"
    footer-github-url: "https://github.com/Peakboard/peakboard-templates.github.io/tree/master/_templates/"
    footer-legal: "法律信息"
    footer-legal-url: "https://peakboard.com/en/legal-notice/"
    search-title: "Peakboard搜索"
    search-results: "搜索结果"
    search-no-results: "未找到相关搜索结果： "
    search-bar-placeholder: "搜索"
    cookie-alert-message: "此网站使用cookies，以确保最佳浏览体验。"
    cookie-alert-button: "允许"
    cookie-alert-link-text: "了解更多"
    cookie-alert-link: "https://peakboard.com/en/privacy-policy/"
    cta-title: "立即试用Peakboard-Designer!"
    cta-subtitle: "下载Peakboard-Designer，在最短的时间内为每个部门定制仪表盘。"
    cta-content: "使用Peakboard-Designer，无论是采用实时图块、语音命令还是经典图表，您都可以快速创建多种仪表盘，实时显示相关信息。方便快捷，一目了然。它可用于生产、仓储物流、IT或是分销部门。"
    cta-link: "https://peakboard.com/zh-hans/peakboard-designer/?utm_source=templates_overview&utm_medium=get_started_button&utm_campaign=templates"
    cta-link-text: "免费下载Peakboard Designer"
algolia:
  application_id: 'XEVVIEZWKI'
  index_name: PEAKBOARD_EPIC_BOARDS
  settings:
    attributesForFaceting: ['title', 'searchable(search-ignore)', 'searchable(lang)', 'searchable(category)', 'searchable(isDraft)', 'searchable(overview_data_sources)']
    searchableAttributes: ['title','unordered(content)','description','search-ignore', 'lang', 'category', 'isDraft', 'overview_data_sources']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - resources
  - docs
  - .idea
  - .idea/*
  - vendor
